"""empty message

Revision ID: 061cf9bfbdbf
Revises: 721da002a97a
Create Date: 2023-08-28 19:35:09.891123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061cf9bfbdbf'
down_revision = '721da002a97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('subtotal')

    # ### end Alembic commands ###
