"""Cargamos base de datos

Revision ID: 37dd8fc9bde5
Revises: 
Create Date: 2023-08-30 23:14:40.748843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37dd8fc9bde5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.Text(), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('nombre_real', sa.String(length=250), nullable=True),
    sa.Column('perfil', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('subtitulo', sa.String(length=300), nullable=True),
    sa.Column('descripcion', sa.String(length=4000), nullable=True),
    sa.Column('url_imagen', sa.String(length=350), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('contrasenha', sa.String(length=250), nullable=False),
    sa.Column('direccion_comprador', sa.String(length=250), nullable=True),
    sa.Column('ciudad_comprador', sa.String(length=250), nullable=True),
    sa.Column('estado_comprador', sa.String(length=250), nullable=True),
    sa.Column('codigo_postal_comprador', sa.String(length=250), nullable=True),
    sa.Column('pais_comprador', sa.String(length=250), nullable=True),
    sa.Column('telefono_comprador', sa.String(length=250), nullable=True),
    sa.Column('valoracion', sa.Integer(), nullable=True),
    sa.Column('valoraciones_positivas', sa.Integer(), nullable=True),
    sa.Column('valoraciones_negativas', sa.Integer(), nullable=True),
    sa.Column('cantidad_de_valoraciones', sa.Integer(), nullable=True),
    sa.Column('cliente_ID_paypal', sa.String(length=250), nullable=True),
    sa.Column('secret_key_paypal', sa.String(length=250), nullable=True),
    sa.Column('isSeller', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('aprobaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('url_imagen', sa.String(length=250), nullable=True),
    sa.Column('artista_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('sello', sa.String(length=250), nullable=True),
    sa.Column('formato', sa.String(length=250), nullable=True),
    sa.Column('pais', sa.String(length=250), nullable=False),
    sa.Column('publicado', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=False),
    sa.Column('estilos', sa.String(length=250), nullable=True),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('estatus', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archivo_mensajes_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=250), nullable=True),
    sa.Column('artista_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('sello', sa.String(length=250), nullable=True),
    sa.Column('formato', sa.String(length=250), nullable=True),
    sa.Column('pais', sa.String(length=250), nullable=False),
    sa.Column('publicado', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=250), nullable=False),
    sa.Column('estilos', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bandeja_de_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.Column('isMessage', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bandeja_de_entrada_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_eliminados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.Column('isMessage', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_enviados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('asunto', sa.String(length=250), nullable=True),
    sa.Column('mensaje', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.String(length=250), nullable=True),
    sa.Column('isMessage', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('precio_envio', sa.Integer(), nullable=True),
    sa.Column('precio_total', sa.Integer(), nullable=True),
    sa.Column('impuesto', sa.Integer(), nullable=True),
    sa.Column('condicion_funda', sa.String(length=250), nullable=True),
    sa.Column('condicion_soporte', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('valorado', sa.Boolean(), nullable=True),
    sa.Column('haveShipping', sa.Boolean(), nullable=True),
    sa.Column('ofertas_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('condicion_funda', sa.String(length=250), nullable=True),
    sa.Column('condicion_soporte', sa.String(length=250), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_articulos',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'articulo_id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('posicion', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('oferta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrito')
    op.drop_table('tracks')
    op.drop_table('pedido_articulos')
    op.drop_table('ofertas')
    op.drop_table('favoritos')
    op.drop_table('coleccion')
    op.drop_table('pedido')
    op.drop_table('mensajes_enviados')
    op.drop_table('mensajes_eliminados')
    op.drop_table('bandeja_de_entrada_admin')
    op.drop_table('bandeja_de_entrada')
    op.drop_table('articulo')
    op.drop_table('archivo_mensajes_admin')
    op.drop_table('aprobaciones')
    op.drop_table('user')
    op.drop_table('home_content')
    op.drop_table('artista')
    # ### end Alembic commands ###
