"""empty message

Revision ID: 4ae370981250
Revises: 909e4731546c
Create Date: 2023-11-12 17:43:24.164579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae370981250'
down_revision = '909e4731546c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios_de_articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('articulo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comentario', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'articulo', ['articulo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios_de_articulo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha')
        batch_op.drop_column('comentario')
        batch_op.drop_column('articulo_id')

    # ### end Alembic commands ###
