"""empty message

Revision ID: 594c81bcf63a
Revises: 0034f162ef71
Create Date: 2023-10-31 14:37:22.703492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '594c81bcf63a'
down_revision = '0034f162ef71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actualizaciones_de_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('fecha',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('videos_de_articulos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_de_articulos', schema=None) as batch_op:
        batch_op.drop_column('posicion')

    with op.batch_alter_table('actualizaciones_de_videos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('posicion')

    # ### end Alembic commands ###
