"""empty message

Revision ID: 680b6cda40c6
Revises: e4c3360f11b9
Create Date: 2023-11-12 16:53:44.646881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680b6cda40c6'
down_revision = 'e4c3360f11b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios_de_articulo_reportados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_escritor', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.String(length=50), nullable=True),
    sa.Column('comentario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_de_reporte', sa.String(length=50), nullable=True),
    sa.Column('user_id_denunciante', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentarios_de_articulo.id'], ),
    sa.ForeignKeyConstraint(['user_id_denunciante'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id_escritor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios_de_articulo_reportados')
    # ### end Alembic commands ###
