"""empty message

Revision ID: 7a6209be9811
Revises: 061cf9bfbdbf
Create Date: 2023-08-29 23:47:25.362077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6209be9811'
down_revision = '061cf9bfbdbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ofertas_ids', sa.ARRAY(sa.Integer()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('ofertas_ids')

    # ### end Alembic commands ###
