"""empty message

Revision ID: 909e4731546c
Revises: bcd8610128d1
Create Date: 2023-11-12 17:41:22.328481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909e4731546c'
down_revision = 'bcd8610128d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios_de_articulo', schema=None) as batch_op:
        batch_op.drop_constraint('comentarios_de_articulo_articulo_id_fkey', type_='foreignkey')
        batch_op.drop_column('articulo_id')
        batch_op.drop_column('fecha')
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios_de_articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('articulo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comentarios_de_articulo_articulo_id_fkey', 'articulo', ['articulo_id'], ['id'])

    # ### end Alembic commands ###
