"""empty message

Revision ID: e4c3360f11b9
Revises: 1ddcd4be5167
Create Date: 2023-11-08 17:19:27.522973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c3360f11b9'
down_revision = '1ddcd4be5167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios_de_articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actualizaciones_de_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_imagen', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion_video', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nombre_canal', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('canal_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('videos_de_articulos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_imagen', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion_video', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nombre_canal', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('canal_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos_de_articulos', schema=None) as batch_op:
        batch_op.drop_column('canal_id')
        batch_op.drop_column('nombre_canal')
        batch_op.drop_column('fecha_creacion_video')
        batch_op.drop_column('url_imagen')

    with op.batch_alter_table('actualizaciones_de_videos', schema=None) as batch_op:
        batch_op.drop_column('canal_id')
        batch_op.drop_column('nombre_canal')
        batch_op.drop_column('fecha_creacion_video')
        batch_op.drop_column('url_imagen')

    op.drop_table('comentarios_de_articulo')
    # ### end Alembic commands ###
