"""empty message

Revision ID: e4e3f2766f2b
Revises: 4ae370981250
Create Date: 2023-11-14 22:07:11.277529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e3f2766f2b'
down_revision = '4ae370981250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actualizaciones_de_videos', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion_video')
        batch_op.drop_column('titulo')
        batch_op.drop_column('fecha')
        batch_op.drop_column('url_imagen')
        batch_op.drop_column('nombre_canal')
        batch_op.drop_column('canal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actualizaciones_de_videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canal_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre_canal', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('url_imagen', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion_video', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
